# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server import util


class InlineObject(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, privatekey_wif=None, file=None):  # noqa: E501
        """InlineObject - a model defined in OpenAPI

        :param privatekey_wif: The privatekey_wif of this InlineObject.  # noqa: E501
        :type privatekey_wif: str
        :param file: The file of this InlineObject.  # noqa: E501
        :type file: file
        """
        self.openapi_types = {
            'privatekey_wif': str,
            'file': file
        }

        self.attribute_map = {
            'privatekey_wif': 'privatekey_wif',
            'file': 'file'
        }

        self._privatekey_wif = privatekey_wif
        self._file = file

    @classmethod
    def from_dict(cls, dikt) -> 'InlineObject':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The inline_object of this InlineObject.  # noqa: E501
        :rtype: InlineObject
        """
        return util.deserialize_model(dikt, cls)

    @property
    def privatekey_wif(self):
        """Gets the privatekey_wif of this InlineObject.


        :return: The privatekey_wif of this InlineObject.
        :rtype: str
        """
        return self._privatekey_wif

    @privatekey_wif.setter
    def privatekey_wif(self, privatekey_wif):
        """Sets the privatekey_wif of this InlineObject.


        :param privatekey_wif: The privatekey_wif of this InlineObject.
        :type privatekey_wif: str
        """

        self._privatekey_wif = privatekey_wif

    @property
    def file(self):
        """Gets the file of this InlineObject.


        :return: The file of this InlineObject.
        :rtype: file
        """
        return self._file

    @file.setter
    def file(self, file):
        """Sets the file of this InlineObject.


        :param file: The file of this InlineObject.
        :type file: file
        """

        self._file = file
