# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server import util


class RequestUploadTextModel(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, mnemonic_words=None, message=None):  # noqa: E501
        """RequestUploadTextModel - a model defined in OpenAPI

        :param mnemonic_words: The mnemonic_words of this RequestUploadTextModel.  # noqa: E501
        :type mnemonic_words: str
        :param message: The message of this RequestUploadTextModel.  # noqa: E501
        :type message: str
        """
        self.openapi_types = {
            'mnemonic_words': str,
            'message': str
        }

        self.attribute_map = {
            'mnemonic_words': 'mnemonic_words',
            'message': 'message'
        }

        self._mnemonic_words = mnemonic_words
        self._message = message

    @classmethod
    def from_dict(cls, dikt) -> 'RequestUploadTextModel':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The RequestUploadTextModel of this RequestUploadTextModel.  # noqa: E501
        :rtype: RequestUploadTextModel
        """
        return util.deserialize_model(dikt, cls)

    @property
    def mnemonic_words(self):
        """Gets the mnemonic_words of this RequestUploadTextModel.


        :return: The mnemonic_words of this RequestUploadTextModel.
        :rtype: str
        """
        return self._mnemonic_words

    @mnemonic_words.setter
    def mnemonic_words(self, mnemonic_words):
        """Sets the mnemonic_words of this RequestUploadTextModel.


        :param mnemonic_words: The mnemonic_words of this RequestUploadTextModel.
        :type mnemonic_words: str
        """

        self._mnemonic_words = mnemonic_words

    @property
    def message(self):
        """Gets the message of this RequestUploadTextModel.


        :return: The message of this RequestUploadTextModel.
        :rtype: str
        """
        return self._message

    @message.setter
    def message(self, message):
        """Sets the message of this RequestUploadTextModel.


        :param message: The message of this RequestUploadTextModel.
        :type message: str
        """

        self._message = message
