# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server import util


class ResponseUploadToCloudModel(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, code=None, file_id=None, encrypt_hex=None):  # noqa: E501
        """ResponseUploadToCloudModel - a model defined in OpenAPI

        :param code: The code of this ResponseUploadToCloudModel.  # noqa: E501
        :type code: int
        :param file_id: The file_id of this ResponseUploadToCloudModel.  # noqa: E501
        :type file_id: str
        :param encrypt_hex: The encrypt_hex of this ResponseUploadToCloudModel.  # noqa: E501
        :type encrypt_hex: str
        """
        self.openapi_types = {
            'code': int,
            'file_id': str,
            'encrypt_hex': str
        }

        self.attribute_map = {
            'code': 'code',
            'file_id': 'datetime_uid',
            'encrypt_hex': 'encrypt_hex'
        }

        self._code = code
        self._file_id = file_id
        self._encrypt_hex = encrypt_hex

    @classmethod
    def from_dict(cls, dikt) -> 'ResponseUploadToCloudModel':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ResponseUploadToCloudModel of this ResponseUploadToCloudModel.  # noqa: E501
        :rtype: ResponseUploadToCloudModel
        """
        return util.deserialize_model(dikt, cls)

    @property
    def code(self):
        """Gets the code of this ResponseUploadToCloudModel.


        :return: The code of this ResponseUploadToCloudModel.
        :rtype: int
        """
        return self._code

    @code.setter
    def code(self, code):
        """Sets the code of this ResponseUploadToCloudModel.


        :param code: The code of this ResponseUploadToCloudModel.
        :type code: int
        """

        self._code = code

    @property
    def file_id(self):
        """Gets the file_id of this ResponseUploadToCloudModel.


        :return: The file_id of this ResponseUploadToCloudModel.
        :rtype: str
        """
        return self._file_id

    @file_id.setter
    def file_id(self, file_id):
        """Sets the file_id of this ResponseUploadToCloudModel.


        :param file_id: The file_id of this ResponseUploadToCloudModel.
        :type file_id: str
        """

        self._file_id = file_id

    @property
    def encrypt_hex(self):
        """Gets the encrypt_hex of this ResponseUploadToCloudModel.


        :return: The encrypt_hex of this ResponseUploadToCloudModel.
        :rtype: str
        """
        return self._encrypt_hex

    @encrypt_hex.setter
    def encrypt_hex(self, encrypt_hex):
        """Sets the encrypt_hex of this ResponseUploadToCloudModel.


        :param encrypt_hex: The encrypt_hex of this ResponseUploadToCloudModel.
        :type encrypt_hex: str
        """

        self._encrypt_hex = encrypt_hex