# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server import util


class ResponseAddAddressModel(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, code=None, message=None):  # noqa: E501
        """ResponseAddAddressModel - a model defined in OpenAPI

        :param code: The code of this ResponseAddAddressModel.  # noqa: E501
        :type code: int
        :param message: The message of this ResponseAddAddressModel.  # noqa: E501
        :type message: str
        """
        self.openapi_types = {
            'code': int,
            'message': str
        }

        self.attribute_map = {
            'code': 'code',
            'message': 'message'
        }

        self._code = code
        self._message = message

    @classmethod
    def from_dict(cls, dikt) -> 'ResponseAddAddressModel':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ResponseAddAddressModel of this ResponseAddAddressModel.  # noqa: E501
        :rtype: ResponseAddAddressModel
        """
        return util.deserialize_model(dikt, cls)

    @property
    def code(self):
        """Gets the code of this ResponseAddAddressModel.


        :return: The code of this ResponseAddAddressModel.
        :rtype: int
        """
        return self._code

    @code.setter
    def code(self, code):
        """Sets the code of this ResponseAddAddressModel.


        :param code: The code of this ResponseAddAddressModel.
        :type code: int
        """

        self._code = code

    @property
    def message(self):
        """Gets the message of this ResponseAddAddressModel.


        :return: The message of this ResponseAddAddressModel.
        :rtype: str
        """
        return self._message

    @message.setter
    def message(self, message):
        """Sets the message of this ResponseAddAddressModel.


        :param message: The message of this ResponseAddAddressModel.
        :type message: str
        """

        self._message = message
