# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server import util


class ResponseUploadModel(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, code=None, txid=None):  # noqa: E501
        """ResponseUploadModel - a model defined in OpenAPI

        :param code: The code of this ResponseUploadModel.  # noqa: E501
        :type code: int
        :param txid: The txid of this ResponseUploadModel.  # noqa: E501
        :type txid: str
        """
        self.openapi_types = {
            'code': int,
            'txid': str
        }

        self.attribute_map = {
            'code': 'code',
            'txid': 'txid'
        }

        self._code = code
        self._txid = txid

    @classmethod
    def from_dict(cls, dikt) -> 'ResponseUploadModel':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ResponseUploadModel of this ResponseUploadModel.  # noqa: E501
        :rtype: ResponseUploadModel
        """
        return util.deserialize_model(dikt, cls)

    @property
    def code(self):
        """Gets the code of this ResponseUploadModel.


        :return: The code of this ResponseUploadModel.
        :rtype: int
        """
        return self._code

    @code.setter
    def code(self, code):
        """Sets the code of this ResponseUploadModel.


        :param code: The code of this ResponseUploadModel.
        :type code: int
        """

        self._code = code

    @property
    def txid(self):
        """Gets the txid of this ResponseUploadModel.


        :return: The txid of this ResponseUploadModel.
        :rtype: str
        """
        return self._txid

    @txid.setter
    def txid(self, txid):
        """Sets the txid of this ResponseUploadModel.


        :param txid: The txid of this ResponseUploadModel.
        :type txid: str
        """

        self._txid = txid
